name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Adicione este passo para instalar o utilitário port knocking
      - name: Install Port Knocking
        run: sudo apt-get update && sudo apt-get install -y knockd
      - name: ⚠️Verificando knockd...
        run: knockd --version || echo "knockd não está instalado ⛔"
      - uses: actions/checkout@v2
      - name: Deploy to main
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: './'
          target: /home/${{ secrets.SSH_USER }}/public_html
